/*
 *   sfcnFindSpi.c Simple C-MEX S-function for function call.
 *
 *   ABSTRACT:
 *     The purpose of this sfunction is to call a simple legacy
 *     function during simulation:
 *
 *        double y1 = dummy(int8 p1)
 *
 *   Simulink version           : 8.3 (R2014a) 27-Dec-2013
 *   C source code generated on : 08-Apr-2015 21:24:47

 * THIS S-FUNCTION IS GENERATED BY THE LEGACY CODE TOOL AND MAY NOT WORK IF MODIFIED

 */


/*
 * Must specify the S_FUNCTION_NAME as the name of the S-function.
 */
#define S_FUNCTION_NAME                sfcnNokiaDisp5110
#define S_FUNCTION_LEVEL               2

/*
 * Need to include simstruc.h for the definition of the SimStruct and
 * its associated macro definitions.
 */
#include "simstruc.h"
#define EDIT_OK(S, P_IDX) \
 (!((ssGetSimMode(S)==SS_SIMMODE_SIZES_CALL_ONLY) && mxIsEmpty(ssGetSFcnParam(S, P_IDX))))
#define SAMPLE_TIME                    (ssGetSFcnParam(S, 2))
#define NUM_PARAM                      13
#define isDWorkNeeded                  ((!((ssRTWGenIsCodeGen(S) || ssGetSimMode(S)==SS_SIMMODE_EXTERNAL) && isSimulationTarget==0)) || ssIsRapidAcceleratorActive(S))
#define MDL_CHECK_PARAMETERS
#if defined(MDL_CHECK_PARAMETERS) && defined(MATLAB_MEX_FILE)
 
static bool IsRealMatrix(const mxArray * const m);

/* Function: mdlCheckParameters ===========================================
 * Abstract:
 *    mdlCheckParameters verifies new parameter settings whenever parameter
 *    change or are re-evaluated during a simulation. When a simulation is
 *    running, changes to S-function parameters can occur at any time during
 *    the simulation loop.
 */
static void mdlCheckParameters(SimStruct *S)
{
  // Parameters
  // NumInp,Format,SampleTime,puSpiTags,VCC,SCE,RST,DC,LED
  /*
   * Check the parameter 1 - NumInputs
   */

  /*
   * Check the parameter 3 (sample time)
   */
  if EDIT_OK(S, 2) {
    const double * sampleTime = NULL;
    const size_t stArraySize = mxGetM(SAMPLE_TIME) * mxGetN(SAMPLE_TIME);

    /* Sample time must be a real scalar value or 2 element array. */
    if (IsRealMatrix(SAMPLE_TIME) &&
        (stArraySize == 1 || stArraySize == 2) ) {
      sampleTime = mxGetPr(SAMPLE_TIME);
    } else {
      ssSetErrorStatus(S,
                       "Invalid sample time. Sample time must be a real scalar value or an array of two real values.");
      return;
    }

    if (sampleTime[0] < 0.0 && sampleTime[0] != -1.0) {
      ssSetErrorStatus(S,
                       "Invalid sample time. Period must be non-negative or -1 (for inherited).");
      return;
    }

    if (stArraySize == 2 && sampleTime[0] > 0.0 &&
        sampleTime[1] >= sampleTime[0]) {
      ssSetErrorStatus(S,
                       "Invalid sample time. Offset must be smaller than period.");
      return;
    }

    if (stArraySize == 2 && sampleTime[0] == -1.0 && sampleTime[1] != 0.0) {
      ssSetErrorStatus(S,
                       "Invalid sample time. When period is -1, offset must be 0.");
      return;
    }

    if (stArraySize == 2 && sampleTime[0] == 0.0 &&
        !(sampleTime[1] == 1.0)) {
      ssSetErrorStatus(S,
                       "Invalid sample time. When period is 0, offset must be 1.");
      return;
    }
  }
}
#endif

/* Function: mdlInitializeSizes ===========================================
 * Abstract:
 *    The sizes information is used by Simulink to determine the S-function
 *    block's characteristics (number of inputs, outputs, states, etc.).
 */
static void mdlInitializeSizes(SimStruct *S)
{
  /* Lokale Variablen */
  int32_T i, n;
  /* Number of expected parameters */
  ssSetNumSFcnParams(S, NUM_PARAM);

#if defined(MATLAB_MEX_FILE)

  if (ssGetNumSFcnParams(S) == ssGetSFcnParamsCount(S)) {
    /*
     * If the number of expected input parameters is not equal
     * to the number of parameters entered in the dialog box return.
     * Simulink will generate an error indicating that there is a
     * parameter mismatch.
     */
    mdlCheckParameters(S);
    if (ssGetErrorStatus(S) != NULL) {
      return;
    }
  } else {
    /* Return if number of expected != number of actual parameters */
    return;
  }

#endif

  for(i=0;i<=(NUM_PARAM-1);i++)
  {
    /* Set the parameter's tunability */
    ssSetSFcnParamTunable(S, i, SS_PRM_NOT_TUNABLE);
  }
  /*
   * Set the number of pworks.
   */
  ssSetNumPWork(S, 0);

  /*
   * Set the number of dworks.
   */
  if (!ssSetNumDWork(S, 0))
    return;

  /*
   * Set the number of input ports.
   */
  n = (int32_T) mxGetPr(ssGetSFcnParam(S,0))[0];
  if (!ssSetNumInputPorts(S, n))
    return;

  /*
   * Configure the input ports
   */
  for(i=0;i<n;i++)
  {
      ssSetInputPortDataType            (S, i, DYNAMICALLY_TYPED);
      ssSetInputPortWidth               (S, i, 1);
      ssSetInputPortComplexSignal       (S, i, COMPLEX_NO);
      ssSetInputPortDirectFeedThrough   (S, i, 1);
      ssSetInputPortAcceptExprInRTW     (S, i, 1);
      ssSetInputPortOverWritable        (S, i, 1);
      ssSetInputPortOptimOpts           (S, i, SS_REUSABLE_AND_LOCAL);
      ssSetInputPortRequiredContiguous  (S, i, 1);
  }

  /*
   * Set the number of output ports.
   */
  if (!ssSetNumOutputPorts(S, 0))
    return;

  /*
   * NOT IN USE Configure the output port 1
   */
  //ssSetOutputPortDataType(S, 0, SS_DOUBLE);
  //ssSetOutputPortWidth(S, 0, 1);
  //ssSetOutputPortComplexSignal(S, 0, COMPLEX_NO);
  //ssSetOutputPortOptimOpts(S, 0, SS_REUSABLE_AND_LOCAL);
  //ssSetOutputPortOutputExprInRTW(S, 0, 1);

  /*
   * Register reserved identifiers to avoid name conflict
   */
  if (ssRTWGenIsCodeGen(S) || ssGetSimMode(S)==SS_SIMMODE_EXTERNAL) {
    /*
     * Register reserved identifier for OutputFcnSpec
     */
    //ssRegMdlInfo(S, "dummy", MDL_INFO_ID_RESERVED, 0, 0, ssGetPath(S));
  }

  /*
   * This S-function can be used in referenced model simulating in normal mode.
   */
  ssSetModelReferenceNormalModeSupport(S, MDL_START_AND_MDL_PROCESS_PARAMS_OK);

  /*
   * Set the number of sample time.
   */
  ssSetNumSampleTimes(S, 1);

  /*
   * All options have the form SS_OPTION_<name> and are documented in
   * matlabroot/simulink/include/simstruc.h. The options should be
   * bitwise or'd together as in
   *   ssSetOptions(S, (SS_OPTION_name1 | SS_OPTION_name2))
   */
  ssSetOptions(S,
               SS_OPTION_USE_TLC_WITH_ACCELERATOR |
               SS_OPTION_CAN_BE_CALLED_CONDITIONALLY |
               SS_OPTION_EXCEPTION_FREE_CODE |
               SS_OPTION_WORKS_WITH_CODE_REUSE |
               SS_OPTION_SFUNCTION_INLINED_FOR_RTW |
               SS_OPTION_DISALLOW_CONSTANT_SAMPLE_TIME);
  ssSetSimulinkVersionGeneratedIn(S, "8.3");
}

/* Function: mdlInitializeSampleTimes =====================================
 * Abstract:
 *    This function is used to specify the sample time(s) for your
 *    S-function. You must register the same number of sample times as
 *    specified in ssSetNumSampleTimes.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
  double * const sampleTime = mxGetPr(SAMPLE_TIME);
  const  size_t stArraySize = mxGetM(SAMPLE_TIME) * mxGetN(SAMPLE_TIME);
  ssSetSampleTime(S, 0, sampleTime[0]);
  if (stArraySize == 1) {
    ssSetOffsetTime(S, 0, (sampleTime[0] == CONTINUOUS_SAMPLE_TIME?
      FIXED_IN_MINOR_STEP_OFFSET: 0.0));
  } else {
    ssSetOffsetTime(S, 0, sampleTime[1]);
  }

#if defined(ssSetModelReferenceSampleTimeDefaultInheritance)

  ssSetModelReferenceSampleTimeDefaultInheritance(S);

#endif

}

#define MDL_SET_WORK_WIDTHS
#if defined(MDL_SET_WORK_WIDTHS) && defined(MATLAB_MEX_FILE)

/* Function: mdlSetWorkWidths =============================================
 * Abstract:
 *      The optional method, mdlSetWorkWidths is called after input port
 *      width, output port width, and sample times of the S-function have
 *      been determined to set any state and work vector sizes which are
 *      a function of the input, output, and/or sample times.
 *
 *      Run-time parameters are registered in this method using methods
 *      ssSetNumRunTimeParams, ssSetRunTimeParamInfo, and related methods.
 */
static void mdlSetWorkWidths(SimStruct *S)
{
  /* Set number of run-time parameters */
  //if (!ssSetNumRunTimeParams(S, 2))
  //  return;

  /*
   * Register the run-time parameter 1
   */
  //ssRegDlgParamAsRunTimeParam(S, 0, 0, "p1", ssGetDataTypeId(S, "int8"));
}
#endif

#define MDL_RTW
void mdlRTW(SimStruct *S)
{
    int32_T numPorts = (int32_T) mxGetPr(ssGetSFcnParam(S,0))[0];
    
    //NumInp,puSpiTags,SampleTime,VCC,SCE,RST,DC,LED,FormatZ1,FormatZ2,FormatZ3,FormatZ4,FormatZ5
    //     0,        1,         2,  3,  4,  5, 6,  7,       8,       9,      10,      11,      12 
    if (!ssWriteRTWParamSettings(S, 12,
                    SSWRITE_VALUE_DTYPE_NUM,  "numPorts",   &numPorts, DTINFO(SS_INT32, COMPLEX_NO),
                    SSWRITE_VALUE_STR,        "tagSpi",     mxArrayToString(ssGetSFcnParam(S,1)),
                    SSWRITE_VALUE_STR,        "VCC",        mxArrayToString(ssGetSFcnParam(S,3)),
                    SSWRITE_VALUE_STR,        "SCE",        mxArrayToString(ssGetSFcnParam(S,4)),
                    SSWRITE_VALUE_STR,        "RST",        mxArrayToString(ssGetSFcnParam(S,5)),
                    SSWRITE_VALUE_STR,        "DC",         mxArrayToString(ssGetSFcnParam(S,6)),
                    SSWRITE_VALUE_STR,        "LED",        mxArrayToString(ssGetSFcnParam(S,7)),
                    SSWRITE_VALUE_STR,        "FormatZ1",   mxArrayToString(ssGetSFcnParam(S,8)),
                    SSWRITE_VALUE_STR,        "FormatZ2",   mxArrayToString(ssGetSFcnParam(S,9)),
                    SSWRITE_VALUE_STR,        "FormatZ3",   mxArrayToString(ssGetSFcnParam(S,10)),
                    SSWRITE_VALUE_STR,        "FormatZ4",   mxArrayToString(ssGetSFcnParam(S,11)),
                    SSWRITE_VALUE_STR,        "FormatZ5",   mxArrayToString(ssGetSFcnParam(S,12))
            ))
    {  
            ssSetErrorStatus(S,"ssWriteRTWParamSettings error in mdlRTW");
            return;
    }
}

#define MDL_START
#if defined(MDL_START)

/* Function: mdlStart =====================================================
 * Abstract:
 *    This function is called once at start of model execution. If you
 *    have states that should be initialized once, this is the place
 *    to do it.
 */
static void mdlStart(SimStruct *S)
{
  /*
   * Get access to Parameter/Input/Output/DWork/size information
   */
}

#endif

/* Function: mdlOutputs ===================================================
 * Abstract:
 *    In this function, you compute the outputs of your S-function
 *    block. Generally outputs are placed in the output vector(s),
 *    ssGetOutputPortSignal.
 */
static void mdlOutputs(SimStruct *S, int_T tid)
{
  /*
   * Get access to Parameter/Input/Output/DWork/size information
   */
  //ssPrintf("Param 0, CS  %s \n", mxArrayToString(ssGetSFcnParam(S,0)));
  //ssPrintf("Param 1, ST  %i \n", (int32_T) mxGetPr(ssGetSFcnParam(S,1))[0]);
  //ssPrintf("Param 2, SampleTime %i \n", (int32_T) mxGetPr(ssGetSFcnParam(S,2))[0]);
  //ssPrintf("Param 3, SPI %s \n",  mxArrayToString(ssGetSFcnParam(S,3)));

  /*
   * Call the legacy code function
   */
  //*y1 = dummy( *p1);
}

/* Function: mdlTerminate =================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.
 */
static void mdlTerminate(SimStruct *S)
{
}


/* Function: IsRealMatrix =================================================
 * Abstract:
 *      Verify that the mxArray is a real (double) finite matrix
 */
static bool IsRealMatrix(const mxArray * const m)
{
  if (mxIsNumeric(m) &&
      mxIsDouble(m) &&
      !mxIsLogical(m) &&
      !mxIsComplex(m) &&
      !mxIsSparse(m) &&
      !mxIsEmpty(m) &&
      mxGetNumberOfDimensions(m) == 2) {
    const double * const data = mxGetPr(m);
    const size_t numEl = mxGetNumberOfElements(m);
    size_t i;
    for (i = 0; i < numEl; i++) {
      if (!mxIsFinite(data[i])) {
        return(false);
      }
    }

    return(true);
  } else {
    return(false);
  }
}

/*
 * Required S-function trailer
 */
#ifdef MATLAB_MEX_FILE
# include "simulink.c"
#else
# include "cg_sfun.h"
#endif
